apiVersion: v1
kind: ConfigMap
metadata:
  name: doc-router-config
  namespace: doc-router
data:
  ENV: "prod"
  MONGODB_URI: "mongodb://admin:admin@doc-router-mongodb:27017?authSource=admin"
  FASTAPI_ROOT_PATH: "/fastapi"
  NEXTAUTH_URL: "http://localhost:3000"
  NEXT_PUBLIC_FASTAPI_FRONTEND_URL: "http://localhost:8000"
  FASTAPI_BACKEND_URL: "http://doc-router-backend:8000"
  N_WORKERS: "1"
  CORS_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"
  # Add other non-sensitive configuration here
  # For sensitive values, use Secrets (see secret.yaml)

